const BASE_URL = process.env.REACT_APP_BASE_URL;
const REDIRECT_URI = process.env.REACT_APP_FRONT_REDIRECT_URL;
const LOGIN_URI = process.env.REACT_APP_FRONT_LOGIN_URL;
const GOOGLE_CLIENT_SECRET = process.env.REACT_APP_GOOGLE_CLIENT_SECRET;
const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
const GOOGLE_LOGIN_REQUEST_URL = process.env.REACT_APP_GOOGLE_LOGIN_REQUEST_URL;
const MAPBOX_TOKEN = process.env.REACT_APP_MAPBOX_TOKEN;
const MAPBOX_STYLE = process.env.REACT_APP_MAPBOX_STYLE;
const MAPBOX_ZOOM = process.env.REACT_APP_MAPBOX_ZOOM;
export {
  BASE_URL,
  REDIRECT_URI,
  LOGIN_URI,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_LOGIN_REQUEST_URL,
  MAPBOX_TOKEN,
  MAPBOX_STYLE,
  MAPBOX_ZOOM,
};
