const BASE_URL = process.env.REACT_APP_BASE_URL;
const FRONT_LOGIN_URL = process.env.REACT_APP_FRONT_LOGIN_URL;
const GOOGLE_CLIENT_SECRET = process.env.REACT_APP_GOOGLE_CLIENT_SECRET;
const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
const MAPBOX_TOKEN = process.env.REACT_APP_MAPBOX_TOKEN;
const MAPBOX_STYLE = process.env.REACT_APP_MAPBOX_STYLE;
const MAPBOX_ZOOM = process.env.REACT_APP_MAPBOX_ZOOM;
const SNS_TEST_URL = process.env.REACT_APP_SNS_TEST_URL;

export {
  BASE_URL,
  FRONT_LOGIN_URL,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  MAPBOX_TOKEN,
  MAPBOX_STYLE,
  MAPBOX_ZOOM,
  SNS_TEST_URL,
};
