const BASE_URL = process.env.REACT_APP_BASE_URL;
const REDIRECT_URI = process.env.REACT_APP_FRONT_REDIRECT_URL;
const GOOGLE_CLIENT_SECRET = process.env.REACT_APP_GOOGLE_CLIENT_SECRET;
const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
const { CHATBOT_SECRET } = process.env;
export {
  BASE_URL,
  REDIRECT_URI,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  CHATBOT_SECRET,
};
