export const neighborhoodsVancouver = [
  { title: 'NE Downtown Vancouver', zipcode: 'V6B' },
  { title: 'WE Downtown Vancouver', zipcode: 'V6G' },
  { title: 'SW Downtown Vancouver', zipcode: 'V6Z' },
  { title: 'South West End Area Downtown Vancouver', zipcode: '	V6E' },
  { title: 'Vancouver Pacific Centre Area', zipcode: 'V7Y' },
  { title: 'Vancouver Bentall Centre Area', zipcode: 'V7X' },
  { title: 'Waterfront Coal Harbour Canada Place Area', zipcode: 'V6C' },
  { title: 'Gastown / Chinatown', zipcode: 'V6A' },
  { title: 'East Fairview / South Cambie', zipcode: 'V5Z' },
  { title: 'West Mount Pleasant / West Riley Park', zipcode: 'V5Y' },
  { title: 'SE Oakridge / East Marpole / South Sunset', zipcode: 'V5X' },
  { title: 'SE Riley Park/ SW Kensington / NE Oakridge', zipcode: 'V5W' },
  { title: 'West Kensington / NE Riley Park', zipcode: 'V5V' },
  { title: 'East Mount Pleasant', zipcode: 'V5T' },
  { title: 'Killarney', zipcode: 'V5S' },
  { title: 'South Renfrew Collingwood Area', zipcode: 'V5R' },
  { title: 'SE Kensington Victoria Fraserview Area', zipcode: 'V5P' },
  { title: 'South Grandview- Woodlands / NE Kensington', zipcode: 'V5N' },
  { title: 'North Grandview Woodlands Area', zipcode: 'V5L' },
  { title: 'North Hastings-Sunrise', zipcode: 'V5K' },
  { title: 'South Hastings Sunrise North Renfrew Col Area', zipcode: 'V5M' },
  { title: 'West Fairview Granville Island NE Shaugh Area', zipcode: 'V6H' },
  { title: 'SE Kerrisdale / SW Oakridge / West Marpole', zipcode: 'V6P' },
  { title: 'South Shaughnessy / NW Oakridge / NE Kerrisdale', zipcode: 'V6M' },
  { title: 'Dunbar', zipcode: 'V6N' },
  { title: 'NW Arbutus Ridge', zipcode: 'V6L' },
  { title: 'UBC (University of British Columbia)', zipcode: 'V6T' },
  { title: 'Chaldecutt / South University Endowment Lands', zipcode: 'V6S' },
  { title: 'West Kitsilano Jericho Area', zipcode: 'V6R' },
  { title: 'Central Kitsilano', zipcode: 'V6K' },
  { title: 'NW Shaughnessy / East Kitsilano / Quilchena', zipcode: 'V6J' },
  { title: 'West Vancouver West Area', zipcode: 'V7W' },
  { title: 'West Vancouver South Area', zipcode: 'V7V ' },
  { title: 'West Vancouver Southeast Area', zipcode: 'V7T' },
  { title: 'West Vancouver North Area', zipcode: 'V7S' },
  { title: 'North Vancouver Northwest Area', zipcode: 'V7R' },
  { title: 'North Vancouver Southwest Area', zipcode: 'V7P' },
  { title: 'North Vancouver Northwest Central Area', zipcode: 'V7N' },
  { title: 'North Vancouver Southwest Central Area', zipcode: 'V7M' },
  { title: 'North Vancouver South Central Area', zipcode: 'V7L' },
  { title: 'North Vancouver North Central Area', zipcode: 'V7K' },
  { title: 'North Vancouver East Central Area', zipcode: 'V7J' },
  { title: 'North Vancouver Inner East Area', zipcode: 'V7H' },
  { title: 'North Vancouver Outer East Area', zipcode: 'V7G' },
];
