export const neighborhoods = [
  { title: 'Downtown Vancouver' },
  { title: 'West End' },
  { title: 'Yaletown' },
  { title: 'Gastown' },
  { title: 'Chinatown' },
  { title: 'Kitsilano' },
  { title: 'Granville Island' },
  { title: 'East Vancouver' },
  { title: 'Kerrisdale' },
  { title: 'Dunbar' },
  { title: 'Point Grey' },
  { title: 'UBC (University of British Columbia)' },
  { title: 'Mount Pleasant' },
  { title: 'Riley Park' },
  { title: 'South Granville' },
  { title: 'Marpole' },
  { title: 'Fairview' },
  { title: 'Arbutus Ridge' },
  { title: 'Renfrew' },
  { title: 'Hastings-Sunrise' },
  { title: 'Collingwood' },
  { title: 'Killarney' },
  { title: 'Victoria-Fraserview' },
  { title: 'Sunset' },
  { title: 'South Vancouver' },
  { title: 'Oakridge' },
];
