name: run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # use the Node.js version your project uses

      - name: install dependencies
        run: npm run install-server # this will install your project's dependencies as specified in the package-lock.json

      - name: run tests
        env:
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          PORT: ${{ secrets.PORT }}
        run: npm run test-server # this will run your tests
