name: run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [self-hosted]

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # use the Node.js version your project uses

      - name: install dependencies
        run: cd server && npm install

      # - name: run tests
      #   env:
      #     FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      #     MONGO_URL: ${{ secrets.MONGO_URL }}
      #     PORT: ${{ secrets.PORT }}
      #   run: cd server && npm run test
